name: Fuzzer
on: 
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  autoFuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install astdump
          pip install tensorflow
          pip install scikit-learn
          pip install keras
          pip install constants
          pip install pandas
          
      - name: Run fuzzer 
        working-directory: ./TestOrchestrator4ML-main
        run: python fuzz.py
